# Generated by Django 3.1 on 2020-10-21 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('puesto', '0001_initial'),
        ('users', '0003_auto_20201021_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='area.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='puesto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='puesto.puesto'),
            preserve_default=False,
        ),
    ]
