# Generated by Django 3.1 on 2020-10-21 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puesto', '0001_initial'),
        ('area', '0001_initial'),
        ('users', '0004_auto_20201021_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='area.area'),
        ),
        migrations.AlterField(
            model_name='user',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='puesto.puesto'),
        ),
    ]
